### ISSUE TITLE
Explanation for States

### ISSUE THREAD

**Issue by alzeha** [ticktac-project/tchecker#60]
Hi,

at the file tchecker/zg/state.hh you define

class state_t : public tchecker::ta::state_t

But, of course, a symbolic state is not a location and also not a state in the sense of a TLTS.

Can you explain to me what do you mean here, please? What do you model by tchecker::ta::state_t? A location? A pair, consisting of location and clock valuation? Or something completely different?

Thx.

Best,
Alexander

**Comment by fredher** [comment]
Hi,

`tchecker::ta::state_t` is defined in the file `include/tchecker/ta/state.hh`. There, you will see that a timed automaton state is made of a tuple of locations (one for each process in the model), and a valuation of the bounded integer variables.

TChecker systems consist of a set of processes along with shared variables (bounded integer variables and clocks) and synchronization constraints. Then, we use several layers to build a transition system:
- the `syncprod` layer gives access to the product of the timed processes. A state simply consists of a tuple of locations (one for each process), and a transition consists of a tuple of edges (one for each process that synchronize on the transition). Bounded variables and clocks are ingnored in that layer
- then, at the `ta` layer we interpret bounded integer variables in order to view the system as a single timed automaton, with discrete states and transitions. Transitions have clock guards and clock resets. States have invariants on clocks. Thus, a state at the `ta` level consists of a tuple of locations (in fact, a state from the `syncprod` level) along with a valuation of the bounded integer variables. It is purely discrete. The clocks are not interpreted yet.
- finally, the `zg` layer adds symbolic clock semantics on top of the `ta` layer. States extend `ta` states with a zone. Transitions take guards, updates and invariants into account.

Best regards,
Frédéric

**Comment by alzeha** [comment]
Hi,

ah, so you are indeed representing a location by this state_t (ok, with a few things around it. Mainly that you are using multiple locations at once if you have multiple processes and the integer evaluation).

The line from tchecker/zg/state.hh that I copied says that a symbolic state is a (set of) locations and an integer evaluation. To be honest, I'm not happy with this. In my opinion, a symbolic state consists of a (set of) places, an integer evaluation and a zone. Therefore, I think we should use composition instead of inheritance here.


I am in the process of implementing a strong timed bisimulation algorithm. I have already proven the algorithm and just need to implement and evaluate it before publishing. Of course, I hope that one day my code will be included in the official tchecker repo.

I also have some kind of symbolic state. Right now I inherit from the zg state, which means that I also refer to my symbolic states as (set of) locations. This is giving me a bit of a headache at the moment.


Is it possible for me to change this, or will this be a reason to refuse to merge?

Best,
Alexander

**Comment by fredher** [comment]
Hi,

> The line from tchecker/zg/state.hh that I copied says that a symbolic state is a (set of) locations and
> an integer evaluation. To be honest, I'm not happy with this. In my opinion, a symbolic state consists 
> of a (set of) places, an integer evaluation and a zone.

Please, could you give a precise reference of where we state that "a symbolic state is a (set of) locations and an integer evaluation"?

Moreover, what difference do you make between a location and a place? In TChecker, a location is a position in a process.

> Therefore, I think we should use composition instead of inheritance here.

That's a matter of choice. Inheritance alllows to use type-subtype relations in various situations, for instance, to apply a function defined over `ta::state_t` to `zg::state_t`.

> I also have some kind of symbolic state. Right now I inherit from the zg state, which means that I also 
> refer to my symbolic states as (set of) locations. This is giving me a bit of a headache at the moment.
> 
> Is it possible for me to change this, or will this be a reason to refuse to merge?

Inheriting from `zg::state_t` is obviously not an issue. However I don't understand what you mean by "I also refer to my symbolic states as (set of) locations. This is giving me a bit of a headache at the moment".

Besr regards,
Frédéric

**Comment by alzeha** [comment]
Hi,

first of all: I've solved my problem now, so we can keep this inheritance. I will close this issue.

Nevertheless, in my opinion, inheritance always states an "is-a" relationship. I've learned in my early days that "apple" inherits from "fruit" because an apple is a fruit. If someone asks me for a fruit and I give him an apple, he is fine.

In opposite to that, if someone asks me for a ta::state_t, I'm not sure whether he will be happy when I return a zg::state_t. To be honest: I don't think so...

While it might be true that from a theoretical point of view that inheritance and composition can do the same, it has some practical implications, as you have already pointed out. They provided some headache, which are solved now.

Best,
