### ISSUE TITLE
Results of cppcheck

### ISSUE THREAD

**Issue by alzeha** [ticktac-project/tchecker#62]
Hi,

I am currently analyzing the code using cppcheck. I've found a few lines of code that might look like bugs, but I am not that sure. Before solving them by myself I wanted to ask whether you are interested. If not, just close this issue ;)

After some analysis and removing of false positive, I believe that the following main points, which result into warnings of cppcheck, are relevant:

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/parsing/parsing.hh#L87

the destructor is not virtual. This is surprising since the class contains a virtual method.

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/waiting/waiting.hh#L194

Assert using empty(). As far as I see, empty is not side-effect free. It calls remove_non_waiting_first(). I am not sure, but this looks like the code behaves differently depending on whether assertions are enabled or they are not.

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/waiting/waiting.hh#L207

Same.

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/variables/variables.hh#L233

throw; outside of a catch statement. I think you want to get into the catch part (using exception throwing as part of the control flow), but rethrowing a non-existing exception actually terminates the program (or is undefined, I am not sure about this but it looks weird).

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/src/algorithms/covreach/stats.cc#L17

looks like _stored_states is not initialized

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/clockbounds/solver.hh#L177 
in comparison with
https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/src/clockbounds/solver.cc#L162

the order of x and y is inversed

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/zg/state.hh#L91

the doc says the assignment operator is deleted, but actually it is set to default

https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/zg/state.hh#L96

Same.

The final point is a little bit complicated. It regards the files include/tchecker/utils/shared_objects.hh and include/tchecker/zg/transition.hh.

Due to the fact that assignment and copy operator for transitions are deleted (btw: why?), the copy and assignment operator defined in the shared_objects will behave quite strange.
Of course, they are never used, therefore it won’t have any impact right now. Nevertheless, a new person working with this code might be mislead here, so it might be a good idea to employ some ifs here (or to set the operators to default, as already happened at state.hh).

In case that you fixed (some of) them, please inform me :) In case you don't want to fix any of them, please just close this issue. In case you have any questions, feel free to ask.

Best,
Alexander

**Comment by fredher** [comment]
Dear Alexander,

Thanks a lot for your remarks. I have fixed the issues. Here are some details:

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/parsing/parsing.hh#L87
> 
> the destructor is not virtual. This is surprising since the class contains a virtual method.

Sure, there was a potential error here. The destructor is now `virtual`.

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/waiting/waiting.hh#L194
> 
> Assert using empty(). As far as I see, empty is not side-effect free. It calls remove_non_waiting_first(). I am not sure, but this looks like the code behaves differently depending on whether assertions are enabled or they are not.
> 
> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/waiting/waiting.hh#L207
> 
> Same.

There was no bug since `remove_non_waiting_first()` was called immediately before the assertions. Anyway, as you poiinted out, that was not clear. So I have replaced the assertion to a call to the `empty()` method of the underlying container.

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/variables/variables.hh#L233
> 
> throw; outside of a catch statement. I think you want to get into the catch part (using exception throwing as part of the control flow), but rethrowing a non-existing exception actually terminates the program (or is undefined, I am not sure about this but it looks weird).

True, it is now throwing an exception.

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/src/algorithms/covreach/stats.cc#L17
> 
> looks like _stored_states is not initialized

Yes, this was missing.

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/clockbounds/solver.hh#L177
> 
> in comparison with
> 
> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/src/clockbounds/solver.cc#L162
> 
> the order of x and y is inversed

Rght, the code was correct, but the documentation of the method was not up-to-date.

> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/zg/state.hh#L91
> 
> the doc says the assignment operator is deleted, but actually it is set to default
> 
> https://github.com/ticktac-project/tchecker/blob/9b36a60caeacdbab8cfc7e6c6e47211c6bec80ef/include/tchecker/zg/state.hh#L96
> 
> Same.

There was a error, see below.

> The final point is a little bit complicated. It regards the files include/tchecker/utils/shared_objects.hh and include/tchecker/zg/transition.hh.
> 
> Due to the fact that assignment and copy operator for transitions are deleted (btw: why?), the copy and assignment operator defined in the shared_objects will behave quite strange. Of course, they are never used, therefore it won’t have any impact right now. Nevertheless, a new person working with this code might be mislead here, so it might be a good idea to employ some ifs here (or to set the operators to default, as already happened at state.hh).
> 
> In case that you fixed (some of) them, please inform me :) In case you don't want to fix any of them, please just close this issue. In case you have any questions, feel free to ask.

States and transitions store (intrusive) shared pointers to pool allocated objects. However, states and transitions have no access to the pool. So they cannot make a copy of the objects they point to. So copy and assignment are not safe since:

```c++
state_t s1;
state_t s2{s1};
s2.x = ...;
```

would result in `s1` and `s2` sharing x, and any modification to `x` in `s2` would modify `s1` as well. So the only good solution that I have is to delete copy constructor and assignment. Move constructor and move assignment are ok since they do not result in shared memory.

Notice that the copy constructor, assignment operator, move constructor and move-assignment operator in `tchecker::shared_object_t` explicitely call the corresponding methods of the type `T`. So, if the method is deleted the code will not compile. Hence, I do not expect any strange behavior here. Tell me if i am missing something.

These issues have been fixed in the latest commit. Are you ok with closing this ticket?

Thanks again for your very useful feedback.

Best regards,
Fr´´déric

**Comment by alzeha** [comment]
yes, looks great. thx!
