### ISSUE TITLE
Accessing the invariant of the initial location

### ISSUE THREAD

**Issue by alzeha** [ticktac-project/tchecker#64]
Hi,

currently, I use

`A_trans->tgt_invariant_container()`

with A_trans being a tchecker::zg::transition_sptr_t to access the invariant of the target location. This works fine, as long as I have received that transition using the zg_t::next method.

This does not work for the initial symbolic state, since the target invariant of the initial transition is always empty. I've tried to figure it out by myself but was unable to understand how the next function gets the invariant, some magic is happening there...

So my question is: Given the return value of zg_t::initial(std::vector<tchecker::zg::zg_t::sst_t>), how can I access the invariant of the initial location?

Thanks.

Best,
Alexander

**Comment by fredher** [comment]
Hi Alexander,
There was an inconsistency: the invariant of the state obtained from initial, final, and initialized transitions was put in the source invariant containter instead of the target invariant container. The documentation was not helping much as well. This should be ok now.
Thanks, best regards,
Frédéric
